name: glpi_client
description: A starting point for Dart libraries or applications.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
